version: '3'
services:

  try-it-bash:
    build: 
      context: .
      args:
        IMAGE: alpine
        EXEC_LOCATION: bash
        DEP_INSTALL_CMD: apk add --update curl bash jq
    image: try-it-bash:latest
    command: ["bash", "run.sh"]

  # try-it-go:
  #     image:

  # try-it-java:
  #   build: 
  #     context: .
  #     args:
  #       IMAGE: openjdk:latest
  #       EXEC_LOCATION: java
  #       DEP_INSTALL_CMD: javac InboundIntegration.java
  #   image: try-it-python:latest
  #   command: bash -c "java InboundIntegration"

  # try-it-php:
  #     image: 

  try-it-node:
    build: 
      context: .
      args:
        IMAGE: node:latest
        EXEC_LOCATION: node
        DEP_INSTALL_CMD: npm install
    image: try-it-node:latest
    command: ["bash", "run.sh"]

  try-it-python:
    build: 
      context: .
      args:
        IMAGE: python:3.8
        EXEC_LOCATION: python
        DEP_INSTALL_CMD: pip install -r requirements.txt
    image: try-it-python:latest
    command: ["bash", "run.sh"]

  # try-it-ruby:
  #   build: 
  #     context: .
  #     args:
  #       IMAGE: ruby:2.7.1
  #       EXEC_LOCATION: ruby
  #   image: try-it-ruby:latest
  #   command: bash -c "ruby inbound-integration.rb && ruby outbound-integration.rb"
